backend:
  name: git-gateway
  branch: main

media_folder: assets/uploads
public_folder: /assets/uploads

collections:

  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string

      - label: Custom Slug
        name: custom_slug
        widget: string
        required: true

      - label: Featured Image
        name: image
        widget: image
        required: false

      - label: Excerpt (30 words)
        name: excerpt
        widget: text
        required: false

      - label: Meta Title
        name: meta_title
        widget: string
        required: false

      - label: Meta Description
        name: meta_description
        widget: text
        required: false

      - label: Meta Keywords
        name: meta_keywords
        widget: string
        required: false

      - label: Body
        name: body
        widget: markdown


  - name: pr
    label: PR
    folder: content/pr
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string

      - label: Custom Slug
        name: custom_slug
        widget: string
        required: false

      - label: Featured Image
        name: image
        widget: image
        required: false

      - label: Short Description (30-40 words)
        name: description
        widget: text

      - label: External PR Link
        name: external_link
        widget: string

      - label: Meta Title
        name: meta_title
        widget: string
        required: false

      - label: Meta Description
        name: meta_description
        widget: text
        required: false

      - label: Meta Keywords
        name: meta_keywords
        widget: string
        required: false

      - label: Body (Optional)
        name: body
        widget: markdown
        required: false
